
path:
  src_root: "path/to/raw/aihub/data"
  dst_root: "path/to/intermediate/flattened/data"
  raw_labels: "path/to/intermediate/flattened/data/labels"
  output_dir: "path/to/final/yolo/labels"


dedup:
  hash_size: 8
  threshold: 2  # Hamming distance (lower = stricter removal)

# Class Mapping (Original_ID: Target_ID)
# IDs not listed here will be automatically filtered out.
class_mapping:
  1: 1 # Black Smoke -> Smoke
  2: 1 # White Smoke -> Smoke
  3: 0 # Flame -> Fire

# Conversion Mode: "seg" or "box"
mode: "seg" 
